server:
  port: 5656
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/qa-api java
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:    
        ddl-auto: update 